# -*- coding: utf-8 -*-

import guzzle_sphinx_theme

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode',
              'guzzle_sphinx_theme']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'keepassx'
copyright = u'2013, James Saryerwinnie'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.0.3'
# The full version, including alpha/beta/rc tags.
release = '0.0.3'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'guzzle_sphinx_theme.GuzzleStyle'


# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# Adds an HTML table visitor to apply Bootstrap table classes
html_translator_class = 'guzzle_sphinx_theme.HTMLTranslator'
html_theme_path = guzzle_sphinx_theme.html_theme_path()
html_theme = 'guzzle_sphinx_theme'


html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'keepassxdoc'

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'keepassx', u'keepassx Documentation',
     [u'James Saryerwinnie'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False

# Guzzle theme options (see theme.conf for more information)
html_theme_options = {

    # Set the path to a special layout to include for the homepage
    #"index_template": "special_index.html",

    # Set the name of the project to appear in the nav menu
    "project_nav_name": "python-keepassx",

    # Set your GitHub user and repo to enable GitHub stars links
    "github_user": "jamesls",
    "github_repo": "python-keepassx",

    # Set your Disqus short name to enable comments
    #"disqus_comments_shortname": "my_disqus_comments_short_name",

    # Set you GA account ID to enable tracking
    "google_analytics_account": "UA-28869503-3",

    # Set a custom class to add to the navbar (e.g. navbar-inverse)
    "navbar_class": "",

    # Path to a touch icon
    "touch_icon": "",

    # Set to true to bind left and right key events to turn the page
    "bind_key_events": True,

    # Specify a base_url used to generate sitemap.xml links. If not
    # specified, then no sitemap will be built.
    "base_url": "http://keepassx.readthedocs.org/en/latest/"
}
